from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from api.chat_bot.service import ChatBotService

router = APIRouter(prefix="/chat", tags=["chat"])
service = ChatBotService()

class ChatRequest(BaseModel):
    query: str

class ChatResponse(BaseModel):
    generated_sql: Optional[str] = Field(description="The SQL query generated by the agent")
    final_answer: str = Field(description="The final natural language answer to the user's question")

@router.post("", response_model=ChatResponse)
async def chat(request: ChatRequest):
    """
    Chat with the database using natural language.
    """
    try:
        response = await service.process_query(request.query)
        return response
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
