from langchain_google_genai import ChatGoogleGenerativeAI
from api.config import config
from langchain.agents import create_agent
from api.chat_bot.tools import search_table_details_tool, execute_sql_tool
from pydantic import BaseModel, Field
from typing import Optional, Dict, Any, List
import logging
import json
import re
from typing import Dict, Any

logger = logging.getLogger(__name__)

class ChatBotResponse(BaseModel):
    generated_sql: Optional[str] = Field(description="The SQL query generated by the agent")
    final_answer: Optional[str] = Field(..., description="Formatted answer with \n for line breaks")

class ChatBotService:
    def __init__(self):
        self.llm = ChatGoogleGenerativeAI(
            model="gemini-2.5-flash",
            temperature=0,
            max_retries=1,
            google_api_key=config.google_api_key
        )
        
        self.tools = [search_table_details_tool, execute_sql_tool]
        
        self.system_message = """You are a helpful data assistant. Your goal is to answer user questions by querying a database.
        
                Follow this strict process:
                1. Use `search_table_details_tool` to find relevant tables and schemas based on the user's question.
                2. **CRITICAL SHORT-CIRCUIT:** If `search_table_details_tool` returns no relevant tables (or an empty result), **STOP IMMEDIATELY**. Do NOT generate SQL. Proceed directly to final answer generation (Step 4).
                3. **SQL GENERATION:** Generate a valid SQL SELECT query based ONLY on the schema provided, using the table and column names exactly as provided.
                    a. **SECURITY:** ONLY generate SELECT queries. **NEVER** use DROP, DELETE, UPDATE, INSERT, or ALTER.
                    b. **RAG QUERIES (Rules/Policies):** If the question involves rules, use the `client_rule` table and its `embedding` column. **ALWAYS** join with the `client` table to look up client names (`c.name`).
                    c. **ANALYTICAL QUERIES (Standard):** Generate standard SELECT queries for simple counts, lists, or aggregates.
                    d. **JSON LOGS:** When querying 'process_log', always look into the 'details' JSONB column for customer-specific validation and transformation results.

                    
                    **RAG SQL TEMPLATE (Copy and adapt for rule questions. Filters are optional):**
                    ```sql
                    SELECT cr.rule_content
                    FROM client_rule cr
                    INNER JOIN client c ON cr.client_id = c.id
                    WHERE c.name = '[CLIENT_NAME]' AND cr.process_type = [TYPE_ID] AND cr.is_auto_apply = [BOOL]
                    ORDER BY cr.embedding <-> EMBEDDING_FUNCTION('[USER_QUERY_OR_RULE_CONCEPT]') 
                    LIMIT 3;
                    ```

   
                4. **FINAL ANSWER GENERATION:**
                Return a structured output. The `final_answer` must adapt to the question type:
                - **Summaries:** For process log audits, provide a narrative summary of outcomes.
                - **Lists:** For counts or names, use bullet points (\n•).
                - **Rules:** For client_rule queries, explain the policy and whether it is auto-applied.
                
                **IMPORTANT:** If the SQL result is empty, provide a helpful explanation (e.g., "All fees are currently paid") rather than "No results found."

                Return ONLY valid JSON:
                {
                    "generated_sql": "SELECT ...",
                    "final_answer": "Adaptive response text with \\n"
                }
                """
        
        self.agent = create_agent(self.llm,
                                  tools=self.tools,
                                  system_prompt=self.system_message
                    )



    async def process_query(self, query: str) -> Dict[str, Any]:
        try:
            result = await self.agent.ainvoke({"messages": [{"role": "user", "content": query}]})
            final_response = result["messages"][-1].content
            raw_response = final_response[0]["text"][7:-3]
            formatedresponse : ChatBotResponse = json.loads(raw_response)
            return     formatedresponse
                
        except Exception as e:
            logger.error(f"Error processing query: {e}")
            return {
                "generated_sql": None,
                "final_answer": f"Error: {str(e)}"
            }


# --- Usage Example ---
if __name__ == "__main__":
    # Test the service
    service = ChatBotService()
    
    async def test_queries():
        test_queries = [
            "Which clients have 'Remove leading zero from account number' rule?",
            "Get list of rules",
            "Placement rules for client 123"
        ]
        
        for query in test_queries:
            result = await service.process_query(query)
            print(f"\nQuery: {query}")
            print(f"SQL: {result['generated_sql']}")
            print(f"Answer: {result['final_answer']}")
            print("-" * 80)
    
    import asyncio
    asyncio.run(test_queries())