from fastapi import APIRouter, HTTPException, Depends
from sqlalchemy.orm import Session
from typing import List, Optional
from api.repository.models import Account as AccountModel
from api.repository.db_models import Account as AccountTable
from api.repository.database import get_db
from api.repository.account import AccountRepository

# Create a router for account endpoints
router = APIRouter(prefix="/accounts", tags=["accounts"])

@router.post("", response_model=AccountModel)
def create_account(account: AccountModel, db: Session = Depends(get_db)):
    """Create a new account."""
    repo = AccountRepository(db)
    # Convert Pydantic model to SQLAlchemy model
    # Note: We exclude id as it is autogenerated
    db_account = AccountTable(**account.dict(exclude={"id"}))
    return repo.create(db_account)

@router.get("/{account_id}", response_model=AccountModel)
def get_account(account_id: int, db: Session = Depends(get_db)):
    """Get an account by ID."""
    repo = AccountRepository(db)
    account = repo.get_by_id(account_id)
    if not account:
        raise HTTPException(status_code=404, detail=f"Account with id {account_id} not found")
    return account

@router.get("/number/{account_number}", response_model=AccountModel)
def get_account_by_number(account_number: str, db: Session = Depends(get_db)):
    """Get an account by account number."""
    repo = AccountRepository(db)
    account = repo.get_by_account_number(account_number)
    if not account:
        raise HTTPException(status_code=404, detail=f"Account with number {account_number} not found")
    return account

@router.post("/list", response_model=List[AccountModel])
def get_accounts_by_numbers(account_numbers: List[str], db: Session = Depends(get_db)):
    """Get accounts by a list of account numbers."""
    repo = AccountRepository(db)
    return repo.get_by_account_numbers(account_numbers)

@router.post("/bulk", response_model=List[AccountModel])
def bulk_create_accounts(accounts: List[AccountModel], db: Session = Depends(get_db)):
    """Bulk create accounts."""
    repo = AccountRepository(db)
    # Convert Pydantic models to SQLAlchemy models
    db_accounts = [AccountTable(**account.dict(exclude={"id"})) for account in accounts]
    return repo.bulk_create(db_accounts)

@router.put("/{account_id}", response_model=AccountModel)
def update_account(account_id: int, account: AccountModel, db: Session = Depends(get_db)):
    """Update an account."""
    repo = AccountRepository(db)
    # Exclude id from update
    updated_account = repo.update(account_id, **account.dict(exclude={"id"}, exclude_unset=True))
    if not updated_account:
        raise HTTPException(status_code=404, detail=f"Account with id {account_id} not found")
    return updated_account

@router.delete("/{account_id}")
def delete_account(account_id: int, db: Session = Depends(get_db)):
    """Delete an account."""
    repo = AccountRepository(db)
    success = repo.delete(account_id)
    if not success:
        raise HTTPException(status_code=404, detail=f"Account with id {account_id} not found")
    return {"detail": "Account deleted"}
